# Generated by Django 5.1.3 on 2025-03-04 12:56

import django.db.models.deletion
import netbox_proxbox.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0076_natural_ordering'),
        ('netbox_proxbox', '0007_alter_fastapiendpoint_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='fastapiendpoint',
            name='domain',
            field=netbox_proxbox.fields.DomainField(blank=True, default='proxbox.backend.local', max_length=253, null=True),
        ),
        migrations.AlterField(
            model_name='fastapiendpoint',
            name='ip_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ipam.ipaddress'),
        ),
    ]
