# Generated by Django 5.1.3 on 2025-03-12 13:44

import netbox_proxbox.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_proxbox', '0008_fastapiendpoint_domain_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fastapiendpoint',
            name='domain',
            field=netbox_proxbox.fields.DomainField(blank=True, default='localhost', max_length=253, null=True),
        ),
    ]
