# Generated by Django 5.1.7 on 2025-04-09 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_proxbox', '0009_vmbackup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vmbackup',
            options={'ordering': ('virtual_machine', 'creation_time')},
        ),
    ]
