# Generated by Django 5.1.3 on 2025-03-26 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_proxbox', '0009_syncprocess'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncprocess',
            name='runtime',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
