# Generated by Django 5.1.7 on 2025-04-09 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_proxbox', '0010_alter_vmbackup_options'),
        ('virtualization', '0048_populate_mac_addresses'),
    ]

    operations = [
        migrations.AddField(
            model_name='vmbackup',
            name='storage',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='vmbackup',
            unique_together={('virtual_machine', 'subtype', 'format', 'creation_time', 'volume_id', 'vmid')},
        ),
    ]
