# Generated by Django 5.1.3 on 2025-03-27 12:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_proxbox', '0010_syncprocess_runtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='fastapiendpoint',
            name='server_side_websocket',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fastapiendpoint',
            name='token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fastapiendpoint',
            name='use_websocket',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fastapiendpoint',
            name='websocket_domain',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fastapiendpoint',
            name='websocket_port',
            field=models.PositiveIntegerField(default=8800, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)]),
        ),
    ]
