# Generated by Django 5.1.3 on 2025-03-29 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_proxbox', '0011_fastapiendpoint_server_side_websocket_and_more'),
        ('users', '0009_update_group_perms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='netboxendpoint',
            name='token',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='users.token'),
        ),
    ]
