# Generated by Django 5.1.7 on 2025-04-09 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_proxbox', '0011_vmbackup_storage_alter_vmbackup_unique_together'),
        ('virtualization', '0048_populate_mac_addresses'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vmbackup',
            options={'ordering': ('storage', 'virtual_machine', 'creation_time')},
        ),
        migrations.AlterUniqueTogether(
            name='vmbackup',
            unique_together={('storage', 'virtual_machine', 'subtype', 'format', 'creation_time', 'volume_id', 'vmid')},
        ),
    ]
