# Generated by Django 5.1.3 on 2025-03-31 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_proxbox', '0013_proxmoxendpoint_domain_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxmoxendpoint',
            name='verify_ssl',
            field=models.BooleanField(default=False),
        ),
    ]
