# Generated by Django 5.1.3 on 2025-03-31 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0076_natural_ordering'),
        ('netbox_proxbox', '0014_alter_proxmoxendpoint_verify_ssl'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='proxmoxendpoint',
            unique_together={('name', 'ip_address', 'domain')},
        ),
    ]
