# Generated by Django 5.2.12 on 2026-04-06 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxmox2netbox', '0017_proxmoxendpoint_verify_ssl_default_true'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxmoxnodetypemapping',
            name='custom_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
